### ISSUE TITLE
error starting area orcs and enter this area

### ISSUE THREAD

**Issue by bernnii** [JunkyBulgaria/Sky548New#4]
Crash worldserver.exe

**Comment by FALL1N1** [comment]
give me the crashlog

**Comment by bernnii** [comment]
[rev.1_worldserver.exe_[21-11_8-18-30].txt](https://github.com/JunkyBulgaria/Sky548New/files/40842/rev.1_worldserver.exe_.21-11_8-18-30.txt)

**Comment by FALL1N1** [comment]
InsaneSCore548 ->  no support here mate.

**Comment by bernnii** [comment]
omg its you core only change bt np in you core have this error xd only ask
